---

- name: Install nginx
  hosts: host.name.ip # something that matches anything from the inventory
  become: true

  tasks:

  - name: Create Nginx container
    docker_container:
      name: {{ item.name }}
      image: {{ item.image }}
      ports: {{ item.ports }}
      state: {{ item.state }}
    with_items: "{{ containers }}"

  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: files/nginx/index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: get some bash script
    get_url:
      url: http://mysqltuner.com/mysqltuner.pl
      dest: /usr/local/sbin/mysqltuner

